### ISSUE TITLE
Exclude internal URLs

### ISSUE THREAD

**Issue by Beaufort8** [beck24/embedly_cards#1]
A very nice PlugIn! We use it for a "walled garden" site. In this case, the external service can not render a useful preview. Is it possible to exclude internal links optionally?

**Comment by Beaufort8** [comment]
The Plugin still try to render an internal Bookmarks as an Article-Card (the iFrame shows a Snippet from the Walled-Garden Login-Page).

**Comment by beck24** [comment]
Ah, special case is the bookmarks... fixed in f167fb71b2dfb95f6cc8f5aaaa17e122809dae4b

**Comment by Beaufort8** [comment]
You are the best! Thanx!
